image:
  repository: eclipse-mosquitto
  tag: "2.0.22"
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 400m
    memory: 256Mi
