---
- name: Check if helm is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/helm
  register: helm_binary

- name: Install Helm  # noqa: command-instead-of-module risky-shell-pipe
  ansible.builtin.shell:
    cmd: curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  when: not helm_binary.stat.exists
  changed_when: true
